apiVersion: v1
kind: Namespace
metadata:
  name: ai-platform
  labels:
    name: ai-platform
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: ai-platform-monitoring
  labels:
    name: ai-platform-monitoring
